!ifdef FILE_Constants !eof
FILE_Constants = 1

SCREEN_MIN_X = 24
SCREEN_MAX_XL = 255
SCREEN_MAX_XH = 64
SCREEN_MIN_Y = 50
SCREEN_MAX_Y = 229

PLAYER_STATUS_JUMP_MASK = 1
PLAYER_STATUS_WALKING_MASK = 2
PLAYER_STATUS_DIRECTION_MASK = 4
PLAYER_STATUS_FIRE_MASK = 8
PLAYER_STATUS_HEADBUTT_MASK = 16

CHARACTER_BLANK = 0

PLAYER_COLLISION_BIT_UP = 0
PLAYER_COLLISION_BIT_RIGHT = 1
PLAYER_COLLISION_BIT_DOWN = 2
PLAYER_COLLISION_BIT_LEFT = 3

PLAYER_COLLISION_MASK_UP = 1
PLAYER_COLLISION_MASK_RIGHT = 2
PLAYER_COLLISION_MASK_DOWN = 4
PLAYER_COLLISION_MASK_LEFT = 8